name: CI

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x, 15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: node --version
      - run: npm --version
      - run: docker -v
      - run: docker-compose -v
      - run: docker-compose up -d
      - run: npm install
      - run: npm run lint
      - run: npm run test:types
      - run: npm test
      - run: docker-compose down
    env:
      CI: true
      DB_HOST: localhost
      DB_PORT: 5433
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_SSL: false
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
